How to Build DevSearch library and tool
=======================================

DevSearch top level directory has several subdirectories like src, samples, scripts, docs etc... We run all
clean/compile/run operations from this top level dir. There is a script available at scripts/build.sh

Commands
--------

To clean all binaries, do this
	./scripts/build.sh clean

To freshly compile, do this.
	./scripts/build.sh compile

To run the cli wrapper program, do this.
	./scripts/build.sh run

===============
Eclipse project
===============

This was developed on eclipse IDE, so it can be imported as an eclipse project too. I'm not going into details  